driver/urls.py
from django.conf.urls import url,include
from . import views
app_name='driver'
urlpatterns=[
    url(r'^$',views.home,name='index'),
    url(r'^home/$',views.home,name='homedr'),
    url(r'^setup/$',views.setup,name='profile_setup'),
    url(r'^create_profile',views.create_profile,name='create_profile'),
    url(r'^edit_profile/',views.edit_profile,name='edit_profile'),
    url(r'^edit_location/',views.edit_location,name='edit_location'),
    # url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^ajax/locale/$',views.ajax_locale,name='ajax_locale'),

] 

passenger/urls.py
from django.conf.urls import url,include
from . import views
from django.contrib.auth import views as auth_views
from registration.backends.simple.views import RegistrationView


urlpatterns=[
    url(r'^$',views.homeq,name='homepa'),
    url(r'^setup/$',views.setup,name='profile_setup'),
    url(r'^login/$', auth_views.login,{'template_name': 'login_pas.html'}, name='login'),
    url(r'^register/$',RegistrationView.as_view(),{'template_name': '/registration/registration_for.html'},name='registration_register'),
    url(r'^setup/$',views.setup,name='profile_setup'),
    url(r'^edit_profile/$',views.edit_profile,name='passenger_edit_profile'),
    url(r'^ajax/locale/$',views.ajax_locale,name='ajax_locale'),
    url(r'^ajax/drivers/$',views.ajax_driver,name='ajax_drivers'),
    url(r'^driver/$',views.drivers,name='drivers'),
    url(r'^bookings/(\d+)',views.drivers),
    url(r'^book/(\d+)',views.book)
    
]

ride/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.views.generic import TemplateView
from django.contrib.auth import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', TemplateView.as_view(template_name="index.html")),
    url(r'^passenger/',include('passenger.urls'),name='passenger'),
    url(r'^driver/',include('driver.urls')),
    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^logout/$',views.logout,{"next_page": '/'})

]
if settings.DEBUG:
    urlpatterns+= static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

driver/models.py
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.contrib.auth.models import User
from django_google_maps import fields as map_fields
from passenger.models import Location

# Create your models here.
class Profile(models.Model):
    User=models.OneToOneField(User, on_delete=models.CASCADE)
    # home=models.CharField(max_length=50)
    # destination=models.CharField(max_length=50)
    number_plate=models.CharField(max_length=50)
    color=models.CharField(max_length=50)
    profile_pic=models.ImageField(upload_to='profile/')
    capacity=models.IntegerField()

class LocationDriver(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    home_lat=models.FloatField()
    home_lng=models.FloatField()
    dest_lat=models.FloatField()
    dest_lng=models.FloatField()

class MyPassenger(models.Model):
    driver_user=models.ForeignKey(User,on_delete=models.CASCADE)
    passenger_user=models.IntegerField()

    @classmethod
    def get_driver_passengers(cls,driver):
        passengers=MyPassenger.objects.filter(driver_user=driver)
        return passengers
        
    

passenger/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Passenger_Profile(models.Model):
    User=models.OneToOneField(User, on_delete=models.CASCADE)
    home=models.CharField(max_length=50)
    destination=models.CharField(max_length=50)
    home_lat=models.FloatField()

class Location(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    home_lat=models.FloatField()
    home_lng=models.FloatField()
    dest_lat=models.FloatField()
    dest_lng=models.FloatField()
    
class Booking(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    driver=models.IntegerField()

driver/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Profile

class ProfileForm(forms.ModelForm):
    class Meta:
        model=Profile
        fields=('number_plate','color','capacity','profile_pic')
# class ProfForm(forms.Form):
#     home=forms.CharField(label='Home Area',max_length=30)
#     destination=forms.CharField(label='Destination Area',max_length=30)
#     plate=forms.CharField(label='Number plate',max_length=30)
#     color=forms.CharField(label='Car color',max_length=30)
#     capacity=forms.IntegerField(label='car capacity')

# class ProfilePForm(forms.ModelForm):
#     class Meta:
#         model = Profile
#         fields=('home','destination','number_plate','color','capacity')

passenger/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Passenger_Profile

class ProfileForm(forms.ModelForm):
    class Meta:
        model=Passenger_Profile
        fields=('home','destination')
    def __init__(self,*args,**kwargs):
        super(ProfileForm,self).__init__(*args,**kwargs)
        self.fields['home'].attrs={'id':'sddsfsdf'}

driver/views.py
from django.shortcuts import render,redirect
from .forms import ProfileForm
from .models import Profile,LocationDriver,MyPassenger
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.contrib.auth.models import User
from django.views.decorators.csrf import csrf_exempt


# Create your views here.
def index(request):

    return render(request,'index.html')

@login_required(login_url='/accounts/login/')
def home(request):
    are=Profile.objects.filter(User=request.user)
    # print(len(are))
    if len(are) !=1:
        return redirect('/driver/setup/')
    passengers=MyPassenger.get_driver_passengers(request.user)
    print(len(passengers))
    return render(request,'home.html')

def setup(request):
    form=ProfileForm()
    if request.method=='POST':
        profile_form=ProfileForm(request.POST,files=request.FILES)
        print('<><><>half way<><>>')
    return render(request,'setup_profile.html',{'form':form})

def create_profile(request):
    print ('<><><><><almost there<><><><><')
    form=ProfileForm()
    if request.method=='POST':
        profile_form=ProfileForm(request.POST)
        # profile_form.User=request.user
        # profile_form.Profile.Create()
        Profile.objects.create(User=request.user,home=profile_form.data['home'],number_plate=profile_form.data['number_plate'],destination=profile_form.data['destination'],color=profile_form.data['color'],capacity=profile_form.data['capacity'])

        home=profile_form.data['capacity']
        print(profile_form.data['number_plate'])
    return redirect('homedr')
def edit_profile(request):
    form=ProfileForm()
    if request.method=='POST':
        profile_form=ProfileForm(request.POST,instance=request.user.profile,files=request.FILES)
        
        print('<><><>almost<><><><>')
        if profile_form.is_valid():
            prof=profile_form.save(commit=False)
            prof.User=request.user
            prof.save()
            print('<><><>almost almost <><><><>')
            
            
    return render(request,'edit_profile.html',{'form':form})

def edit_location(request):
    return render(request,'edit_location.html')


@csrf_exempt
def ajax_locale(request):
    home_lat=request.POST.get('home_lat')
    home_lng=request.POST.get('home_lng')
    dest_lat=request.POST.get('dest_lat')
    dest_lng=request.POST.get('dest_lng')
    user_id=request.POST.get('user_id')
    print(user_id)
    # profile_up=Passenger_Profile()
    new_location=LocationDriver(home_lat=home_lat,home_lng=home_lng,dest_lat=dest_lat,dest_lng=dest_lng,user=request.user)
    # new_location.save()
    current_user=User.objects.get(pk=user_id) 
    current_user.locationdriver.home_lat=home_lat
    current_user.locationdriver.home_lng=home_lng
    current_user.locationdriver.dest_lat=dest_lat
    current_user.locationdriver.dest_lng=dest_lng
    
    current_user.locationdriver.save()
    data = {'success': 'your location has been succesfully saved'}

    return JsonResponse(data)

passenger/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required
from .forms import ProfileForm
from .models import Passenger_Profile,Location,Booking
from driver.models import LocationDriver
from django.http import JsonResponse
from django.contrib.auth.models import User
from driver.models import Profile
from django.views.decorators.csrf import csrf_exempt
from .serializer import DriverSerializer
from rest_framework.response import Response
# Create your views here.
@login_required(login_url='/accounts/login/')
def homeq(request):
    are=Passenger_Profile.objects.filter(User=request.user)
    # print(len(are))
    if len(are) !=1:
        return redirect('/passenger/setup/')
    drivers=Profile.objects.all()
    print(len(drivers))
    return render(request,'homepass.html',{'drivers':drivers})

def setup(request):
    form=ProfileForm()
    if request.method=='POST':
        profile_form=ProfileForm(request.POST,files=request.FILES)
        if profile_form.is_valid:
            profile=profile_form.save(commit=False)
            profile.User=request.user
            profile.save()
    return render(request,'setup_profile_passenger.html',{'form':form})
def edit_profile(request):
    form=ProfileForm()
    if request.method=='POST':
        profile_form=ProfileForm(request.POST,instance=request.user.passenger_profile)

        print('<><><>almost<><><><>')
        if profile_form.is_valid():
            prof=profile_form.save(commit=False)
            prof.User=request.user
            # prof.save()
            print('<><><>almost almost <><><><>')
    
    return render(request,'edit_profile_passenger.html',{'form':form})
@csrf_exempt
def ajax_locale(request):
    home_lat=request.POST.get('home_lat')
    home_lng=request.POST.get('home_lng')
    dest_lat=request.POST.get('dest_lat')
    dest_lng=request.POST.get('dest_lng')
    user_id=request.POST.get('user_id')

    profile_up=Passenger_Profile()
    new_location=Location(home_lat=home_lat,home_lng=home_lng,dest_lat=dest_lat,dest_lng=dest_lng)
    current_user=User.objects.get(pk=user_id) 
    current_user.location.home_lat=home_lat
    current_user.location.home_lng=home_lng
    current_user.location.dest_lat=dest_lat
    current_user.location.dest_lng=dest_lng
    
    current_user.location.save()
    data = {'success': 'your location has been succesfully saved'}

    return JsonResponse(data)

def ajax_driver(request):
    all_drivers=LocationDriver.objects.all()
    serializers= DriverSerializer(all_drivers,many=True)
    return Response(serializers.data)

def drivers(request,user_id):
    driver=User.objects.get(pk=user_id)
    my_drivers=Location.objects.filter(user=request.user)
    print(len(my_drivers))
    return render(request,'drivers.html',{'driver':driver})
def book(request,user_id):
    driver=User.objects.get(pk=user_id)    
    new_bookings=Booking(user=request.user,driver=user_id)
    new_bookings.save()
    print('done')
    return render(request,'driversbook.html',{'driver':driver})

passenger/templates/basep.html
{% load bootstrap3 %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% if title %}
    <title>ride with me {{title}}</title>
    {% else %}
    <title>ride with me</title>
    {% endif %}
    {% block styles %}
    {% bootstrap_css %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    {% endblock %}
    
</head>
<body>
    {% include 'navbarr.html' %}
    {% block content %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js">
    </script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAfeePmXWfr3eKsSfpBlGsycHdES0kyOsI&libraries=places"
    async defer></script>
    {% bootstrap_javascript %}
    {% endblock %}

</body>
</html>

passenger/templates/drivers.html
{%extends 'basep.html'%}  
{% load bootstrap3 %} 
{% block content %}
{% load static %}
<div id="content">
    <div id="content-header">
        <div id="breadcrumb">
            <a href="">Home</a>
        </div>
    </div>
    <div class="container-fluid">
        <div class="container profile">
            <div class="row">
                <div class="col-md-8">
                    <div class='map'>
                        <div class="title">
                            <h5><strong><a href="/driver/map">MAP:  </a></strong></h5>
                        </div>
                        <div id="map-sample">

                        </div>
                    </div>
                </div>
                <div class="col-md-4 profile-box">
                    <img src="{{driver.profile.profile_pic.url}}" alt="" class="img-responsive">
                    <div class="title">
                        <h5><strong><a href="/driver/passengers">Profile:  </a>{{driver.username}}</strong></h5>
                    </div>
                    <div class="profile-body">
                        <p><strong>home location:</strong> <span id="home">{{user.profile.home}}</span></p>
                        <p><strong>work location:</strong> <span id="work">Nairobi</span></p>
                        <p><strong>Capacity:</strong> 4</p>
                        
                    </div>
                    <div class="profile-box">
                        <a class="btn btn-primary btn-lg" href="/passenger/book/{{driver.id}}">Book</a> 
                    </div>
                    <div>
                        
                    </div>
                </div>
            </div>    
        </div>

    </div>
  </div>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js">
  </script>
  <!-- <script src = "https://maps.googleapis.com/maps/api/js?key=AIzaSyAfeePmXWfr3eKsSfpBlGsycHdES0kyOsI&libraries=places,geometry"></script> -->
  <script src = "https://maps.googleapis.com/maps/api/js?key=AIzaSyAfeePmXWfr3eKsSfpBlGsycHdES0kyOsI&libraries=places,geometry"></script>
  <script type="text/javascript" src="{% static 'js/profile_setup.js' %}"></script>
  


{% endblock %}

passenger/templates/driversbook.html
{%extends 'basep.html'%}  
{% load bootstrap3 %} 
{% block content %}
{% load static %}
<div id="content">
    <div id="content-header">
        <div id="breadcrumb">
            <a href="">Home</a>
        </div>
    </div>
    <div class="container-fluid">
        <div class="container profile">
            <div class="row">
                <div class="col-md-8">
                    <div class='map'>
                        <div class="title">
                            <h5><strong><a href="/driver/map">MAP:  </a></strong></h5>
                        </div>
                        <div id="map-sample">

                        </div>
                    </div>
                </div>
                <div class="col-md-4 profile-box">
                    <img src="{{driver.profile.profile_pic.url}}" alt="" class="img-responsive">
                    <div class="title">
                        <h5><strong><a href="/driver/passengers">Profile:  </a>{{driver.username}}</strong></h5>
                    </div>
                    <div class="profile-body">
                        <p><strong>home location:</strong> <span id="home">{{user.profile.home}}</span></p>
                        <p><strong>work location:</strong> <span id="work">Nairobi</span></p>
                        <p><strong>Capacity:</strong> 4</p>
                        
                    </div>
                    <div class="profile-box">
                        <a class="btn btn-primary btn-lg" href="/passenger/book/{{driver.id}}">Book</a> 
                    </div>

                </div>
            </div>    
        </div>

    </div>
  </div>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js">
  </script>
  <!-- <script src = "https://maps.googleapis.com/maps/api/js?key=AIzaSyAfeePmXWfr3eKsSfpBlGsycHdES0kyOsI&libraries=places,geometry"></script> -->
  <script src = "https://maps.googleapis.com/maps/api/js?key=AIzaSyAfeePmXWfr3eKsSfpBlGsycHdES0kyOsI&libraries=places,geometry"></script>
  <script type="text/javascript" src="{% static 'js/profile_setup.js' %}"></script>
  


{% endblock %}

passenger/templates/edit_profile_passenger.html
{%extends 'basep.html'%}  
{% load bootstrap3 %} 
{% block content %}
{% load static %}
<div id="content">
  <div id="content-header">
      <div id="breadcrumb">
          <a href="">Home</a>
      </div>
  </div>
  <div class="container-fluid">
      <div class="container profile">
        <h1>Profile update</h1> <p id="user_id">{{user.id}}</p>
        <form method="post" enctype="multipart/form-data">

            <input type="text" id="id_home">
            <input type="text" id="id_destination">
            <input type="submit" value="Submit" id="submit" />
          </form>
      </div>
      <div id="map">

      </div>
  </div>
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js">
</script>
<!-- <script src = "https://maps.googleapis.com/maps/api/js?key=AIzaSyAfeePmXWfr3eKsSfpBlGsycHdES0kyOsI&libraries=places,geometry"></script> -->
<script src = "https://maps.googleapis.com/maps/api/js?key=AIzaSyAfeePmXWfr3eKsSfpBlGsycHdES0kyOsI&libraries=places,geometry"></script>
<script type="text/javascript" src="{% static 'js/profile_setup.js' %}"></script>

  {% endblock %}

passenger/templates/homepass.html
{% extends 'basep.html' %}
{% load static %}
{% block content %}
{{block.super}}
{% load bootstrap3 %}
<div id="content">
    <div id="content-header">
        <div id="breadcrumb">
            <a href="">Home</a>
        </div>
    </div>
    <div class="container-fluid">
        <div class="container profile">
            <div class="row">
                <div class="col-md-8">
                    <div class='map'>
                        <div class="title">
                            <h5><strong><a href="/driver/map">MAP:  </a></strong></h5>
                        </div>
                        <div id="map-sample">

                        </div>
                    </div>
                </div>
                <div class="col-md-4 profile-box">
                    <div class="title">
                        <h5><strong><a href="/driver/passengers">Profile:  </a>{{user.username}}</strong></h5>
                    </div>
                    <div class="profile-body">
                        <p><strong>home location:</strong> <span id="home">{{user.profile.home}}</span></p>
                        <p><strong>work location:</strong> <span id="work">Nairobi</span></p>
                        <p><strong>Capacity:</strong> 4</p>
                        
                    </div>
                    <div class="profile-box">
                            <div class="title">
                                <h5><strong><a href="/driver/passengers">My Passengers</a></strong></h5>
                            </div>
                            <div class="profile-body">
                                <ul>
                                    {% for driver in drivers %}
                                    <p>name: {{driver.User.username}} || location: Uthiru</p>
                                    {% endfor %}
                                </ul>
                                <!-- <p><strong>home location:</strong> <span id="home">{{user.profile.home}}</span></p>
                                <p><strong>work location:</strong> <span id="work">Nairobi</span></p>
                                <p><strong>Capacity:</strong> 4</p> -->
                                
                            </div>  
                        </div>

                </div>
            </div>    
        </div>

    </div>
</div>
<script type="text/javascript" src="{% static 'js/map.js' %}"></script>

{% endblock %}
{% block scripts %}
{{block.super}}
{% bootstrap_javascript %}
{% endblock %}

passenger/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <h1><a href="driver/">Driver</a></h1>
    <h1><a href="passenger/">Passenger</a></h1>
</body>
</html>

passenger/templates/login_pas.html
{%extends "registration/base.html"%}
{% load bootstrap3 %}
{% block content %}
<div class="container">
  <div class="row">
    <!-- Empty div -->
    <div class="col-md-4"></div>
    <div class="col-md-4">
      {% if form.errors %}
        <p> Password or Username is incorrect </p>
      {% endif %}
      <div class="panel panel-default">

        <div class="panel-heading">
          <h3 class="text-center">Sign In</h3>
        </div>
        <div class="panel-body">

          <form  action="/passenger/login/" method="post">
            {% csrf_token %}
            {% bootstrap_form form%}

            <div class="form-group">
              <input type="submit" class="btn btn-primary btn-sm" value="Login">
              <a class="btn btn-primary btn-sm" href="/passenger/accounts/register/">Sign up passenger</a>
            </div>

            <input type="hidden" name="next" value="{{next}}">

          </form>

        </div>

      </div>

    </div>
    <!-- empty div -->
    <div class="col-md-4"></div>
  </div>
</div>

{% endblock %}

passenger/templates/navbarr.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
    <div id="header">
        <h1><a href="/passenger">{{user.username}}</a></h1>
    </div>
    <div class="contaier">
        <div class="navbar navbar-inverse" id="user">
            <ul class="nav navbar-nav">
                {% if user.is_authenticated %}
                <li><a href="/passenger/edit_profile">Profile</a></li>
                <li><a href="/logout">Logout</a></li>
                {% else %}
                <li><a href="/accounts/login">Login</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
    <div id="search">
        <input type="text" placeholder="search here...">  
    </div>
    <div id="sidebar">
        <ul id="side">
            <li class="dash"><a href="/passenger/">HOME</a></li>
            <li class="dash"><a href="/driver/passengers">PASSENGERS</a></li>
            <li class="dash"><a href="">MAP</a></li>
        </ul>
    </div>
</body>
</html>

passenger/templates/setup_profile_passenger.html
{% load bootstrap3 %}
<form action='/passenger/setup/' method="post">
    {% csrf_token %} 
    {% bootstrap_form form%}
    <input type="submit" value="Submit" />
  </form>